# Stile Ruby Omakase per Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Regole da aggiungere o sovrascrivere per lo stile del progetto
#
# # Usare `[a, [b, c]]` e non `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

# date e orari sempre nel fuso di Rails (Roma), mai in quello del server
Rails/Date:
  Enabled: true
  EnforcedStyle: flexible
Rails/TimeZone:
  Enabled: true
  EnforcedStyle: flexible
