# SQLite, versioni 3.8.0 e successive.
#   gem install sqlite3
#
#   La gem SQLite 3 deve essere nel Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: sqlite3
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3
  schema_format: :sql

# Attenzione: il database "test" viene cancellato e rigenerato
# a ogni esecuzione di "rake".
# Non deve coincidere con quello di sviluppo o produzione.
test:
  <<: *default
  database: storage/test.sqlite3
  schema_format: :sql

# Il database di produzione sta in storage/, montato come
# volume Docker persistente in config/deploy.yml.
production:
  primary:
    <<: *default
    database: storage/production.sqlite3
    schema_format: :sql
  cache:
    <<: *default
    database: storage/production_cache.sqlite3
    schema_format: :ruby
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: storage/production_queue.sqlite3
    schema_format: :ruby
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: storage/production_cable.sqlite3
    schema_format: :ruby
    migrations_paths: db/cable_migrate
