# Configurazione effettiva di litestream.
#
# Si può usare `config/initializers/litestream.rb`, che popola
# queste variabili d'ambiente con `rails litestream:replicate`,
#
# oppure gestire a mano variabili e file: in quel caso vanno
# impostate prima di lanciare il comando `replicate`.
#
# Dettagli: https://litestream.io/reference/config/
dbs:
  - path: storage/production.sqlite3
    replicas:
      - type: s3
        bucket: $LITESTREAM_REPLICA_BUCKET
        path: storage/production.sqlite3
        endpoint: $LITESTREAM_REPLICA_ENDPOINT
        region: $LITESTREAM_REPLICA_REGION
        access-key-id: $LITESTREAM_ACCESS_KEY_ID
        secret-access-key: $LITESTREAM_SECRET_ACCESS_KEY
        sync-interval: 60s
        snapshot-interval: 24h
        retention: 168h
